#!/usr/bin/env python3
from pbshax import parallel
from sys import stdin, stdout, stderr
from os import environ as ENV

if __name__ == "__main__":
    verbose = eval(ENV.get('PBSPAR_OUTPUT', 'True'))
    cmds = [l.strip() for l in stdin]
    parallel(cmds, verbose)
