#!/usr/bin/env python3
from pbshax import parallel
from sys import stdin, stdout, stderr
from os import environ as ENV
import argparse as ap

def main():
    a = ap.ArgumentParser(prog="pbsparallel",
                          description="Run commands (from stdin) in parallel (using pbsdsh).")
    a.add_argument("-p", "--procs", default=None, type=int,
                   help="Number of jobs to run in parallel (default: $PBS_NCPUS)")
    a.add_argument("-e", "--procs-per-job", default=1, type=int,
                   help="each job on input uses N processsors (on same node)")
    args = a.parse_args()

    commands = [l.strip() for l in stdin]
    parallel(commands, ncpus=args.procs, threadseach=args.procs_per_job)

if __name__ == "__main__":
    main()
